# Generated by Django 6.0.5 on 2026-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('who_is_it_for', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('math_needed', models.CharField(max_length=200)),
                ('what_you_learn', models.TextField()),
                ('job_market', models.TextField()),
                ('real_life_example', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
